export const GET_ALL_TWEETS_REQUEST = "GET_ALL_TWEETS_REQUEST";
export const GET_ALL_TWEETS_SUCCESS = "GET_ALL_TWEETS_SUCCESS";
export const GET_ALL_TWEETS_FAILURE = "GET_ALL_TWEETS_FAILURE";

export const FOLLOW_USER_REQUEST = "FOLLOW_USER_REQUEST";
export const FOLLOW_USER_SUCCESS = "FOLLOW_USER_SUCCESS";
export const FOLLOW_USER_FAILURE = "FOLLOW_USER_FAILURE";

export const UN_FOLLOW_USER_REQUEST = "UN_FOLLOW_USER_REQUEST";
export const UN_FOLLOW_USER_SUCCESS = "UN_FOLLOW_USER_SUCCESS";
export const UN_FOLLOW_USER_FAILURE = "UN_FOLLOW_USER_FAILURE";

export const ADD_NEW_TWEET_REQUEST = "ADD_NEW_TWEET_REQUEST";
export const ADD_NEW_TWEET_SUCCESS = "ADD_NEW_TWEET_SUCCESS";
export const ADD_NEW_TWEET_FAILURE = "ADD_NEW_TWEET_FAILURE";

export const LIKE_TWEET_REQUEST = "LIKE_TWEET_REQUEST";
export const LIKE_TWEET_SUCCESS = "LIKE_TWEET_SUCCESS";
export const LIKE_TWEET_FAILURE = "LIKE_TWEET_FAILURE";




