export const GET_PROFILE_REQUEST = "GET_PROFILE_REQUEST";
export const GET_PROFILE_SUCCESS = "GET_PROFILE_SUCCESS";
export const GET_PROFILE_FAILURE = "GET_PROFILE_FAILURE";

export const GET_USER_TWEETS_REQUEST = "GET_USER_TWEETS_REQUEST";
export const GET_USER_TWEETS_SUCCESS = "GET_USER_TWEETS_SUCCESS";
export const GET_USER_TWEETS_FAILURE = "GET_USER_TWEETS_FAILURE";
